spring:
  ds:
    aop:
      enabled: true
      order: 1
    p6spy: false
    jdbc-config-decrypt: false
    primary: master
    routing:
      master:
        name: master
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:mem:hikariDB;INIT=RUNSCRIPT FROM 'classpath:schema.sql'
        hikari:
          minimum-idle: 1
          maximum-pool-size: 10

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
